### ISSUE TITLE
non squared thumbs for "other" folders (films etc..)

### ISSUE THREAD

**Issue by Glebelg2** [flozz/cover-thumbnailer#11]
Hi,
I'm unable to generate non-squared thumbnails for other type of folders.
I tried changing the value crop=True by crop=False in the main file at line 518 but after that it does not generate anymore... 
Thanks.

(I 'm on debian testing, Files version 3.38.2)

**Comment by flozz** [comment]
Hello,

Try replacing [line 519](https://github.com/flozz/cover-thumbnailer/blob/master/cover-thumbnailer.py#L519) by `if True:`. It seems there is a check of the output image size :)

**Comment by Glebelg2** [comment]
that line was indeed the "trick" but changing in doesn't solve the problem, however, removing that line works great. Thanks!!

**Comment by Glebelg2** [comment]
yes exactly. 
I'm quite surprised that sandboxed mode for thumbnail generation is distribution dependent...(except if that's not a native/default nautilus feature but an addition of the distrib maintainers)

**Comment by flozz** [comment]
It is strange that Debian not enabled the sandbox but it is good to know :)

I close the issue, open a new one if you have new questions :)
