### ISSUE TITLE
[SOLVED] Error python.pillow 10.0.0-2: module 'PIL.Image' has no attribute 'ANTIALIAS'

### ISSUE THREAD

**Issue by warp4ever** [flozz/cover-thumbnailer#16]
Error from python.pillow 10.0.0-2: module 'PIL.Image' has no attribute 'ANTIALIAS'

Find ANTIALIAS in /usr/bin/cover-thumbnailer, and change this to LANCZOS

Cover-Thumbnailer 0.10.0-2 /Endeavouros / Cinnamon

**Comment by flozz** [comment]
List of removed constants:

https://pillow.readthedocs.io/en/stable/releasenotes/10.0.0.html#constants

**Comment by flozz** [comment]
Fixed in v0.10.1:

https://github.com/flozz/cover-thumbnailer/releases/tag/v0.10.1
