### ISSUE TITLE
Validating source files with sha256sums ..FAILED

### ISSUE THREAD

**Issue by warp4ever** [flozz/cover-thumbnailer#17]
AUR installed version was cover-thumbnailer 0.10.0-2 

> Found cover-thumbnailer-0.10.1.tar.gz
==> Validating source files with sha256sums...
cover-thumbnailer-0.10.1.tar.gz ... FAILED
==> ERROR: One or more files did not pass the validity check!
-> error making: cover-thumbnailer-exit status 1
-> Failed to install the following packages. Manual intervention is required:
cover-thumbnailer - exit status 1

**Comment by warp4ever** [comment]
SOLVED  by copying the sha256sums from [https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=cover-thumbnailer](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=cover-thumbnailer) into the pamac build file

**Comment by flozz** [comment]
Hello,

I am not the maintainer of the AUR package. This issue should be reported directly on the package page:

* https://aur.archlinux.org/packages/cover-thumbnailer

It seems the package is already fixed :)
