### ISSUE TITLE
Thanks this is great! Also, can page turn style be disabled?

### ISSUE THREAD

**Issue by yoghurt-knitter** [flozz/cover-thumbnailer#18]
Great app! Really should be default with Ubuntu.

Wondering if there is a way to disable the bottom left turn back page style?
Would that be done by cover-thumbnailer or system based?

![Untitled](https://github.com/flozz/cover-thumbnailer/assets/106573742/420ff849-44d4-49f9-af54-8e82007a32b1)

Thanks again!

**Comment by yoghurt-knitter** [comment]
I found the file name of what I'm calling page turn style
other_fg.png

**Comment by flozz** [comment]
Hello !

For the Music folders, Cover Thumbnailer should use the CD Case design and not the flipped page one... :thinking: 

Anyway, to "disable" the flipped page effect, you have to replace `other_fg.png` by a completely transparent image :)

**Comment by yoghurt-knitter** [comment]
My music folder is on a different internal drive, not the default Ubuntu folder, so I assume that's why.
That said, looks like it's working as intended now 👍

![Untitled](https://github.com/flozz/cover-thumbnailer/assets/106573742/40c70a3d-28cf-4428-9611-d40d00599352)

I'll go tweak the overlay _fg images now.

Thanks again!

**Comment by flozz** [comment]
You can configure additional music and picture folders from Cover Thumbnailer GUI if you ever want to :)

![image](https://github.com/flozz/cover-thumbnailer/assets/971438/7d7a43aa-50f8-4dd7-811c-fb5aee0fa7ea)
