### ISSUE TITLE
wrong thumbnail image used for music folders

### ISSUE THREAD

**Issue by vishytk** [flozz/cover-thumbnailer#2]
I recently updated to Fedora 27 and installed the latest version on cover-thumbnailer (0.8.4) from git repository.
nautilus = 3.26, nautilus-python = 1.1, python = 2.7.13 and 3.6.3, python-pillow = 4.3.0, PyGI = 3.26.0

When i access the music folder available in "list of folder" from config, only folder containing cover.png is show with thumbnail background and that too using "other_fg.png" instead of "music_bg.png"

It was working fine in Fedora 26.

**Comment by vishytk** [comment]
When i run the commands manually on the terminal, i get following error:
1. in the terminal go to folder containing music albums
2. cover-thumbnailer . ~/.cache/thumbnails
3. nautilus .

(nautilus:8465): GnomeDesktop-WARNING **: Could not remove /tmp/gnome-desktop-thumbnailer-IZHG8Y, thumbnailer \xb0\xf1 left files in directory
W: [/usr/bin/cover-thumbnailer:Conf.import_gnome_conf] Can't find `user-dirs.dirs' file.

**Comment by flozz** [comment]
Hi,

As cover thumbnailer do not find the `~/.config/user-dirs.dirs` file, it does not know which folder is the music folder, so it behave like it is a standard folder.

You can create and fill this file with proper values to make it work again. Here is my `user-dirs.dirs` file if it can help:

```
# This file is written by xdg-user-dirs-update
# If you want to change or add directories, just edit the line you're
# interested in. All local changes will be retained on the next run
# Format is XDG_xxx_DIR="$HOME/yyy", where yyy is a shell-escaped
# homedir-relative path, or XDG_xxx_DIR="/yyy", where /yyy is an
# absolute path. No other format is supported.
# 
XDG_DESKTOP_DIR="$HOME/Bureau"
XDG_DOWNLOAD_DIR="$HOME/Téléchargements"
XDG_TEMPLATES_DIR="$HOME/Modèles"
XDG_PUBLICSHARE_DIR="$HOME/Public"
XDG_DOCUMENTS_DIR="$HOME/Documents"
XDG_MUSIC_DIR="$HOME/Musique"
XDG_PICTURES_DIR="$HOME/Images"
XDG_VIDEOS_DIR="$HOME/Vidéos
```

**Comment by vishytk** [comment]
user-dirs.dirs file exists

# This file is written by xdg-user-dirs-update
# If you want to change or add directories, just edit the line you're
# interested in. All local changes will be retained on the next run
# Format is XDG_xxx_DIR="$HOME/yyy", where yyy is a shell-escaped
# homedir-relative path, or XDG_xxx_DIR="/yyy", where /yyy is an
# absolute path. No other format is supported.
# 
XDG_DESKTOP_DIR="$HOME/Desktop"
XDG_DOWNLOAD_DIR="$HOME/Downloads"
XDG_TEMPLATES_DIR="$HOME/Templates"
XDG_PUBLICSHARE_DIR="$HOME/Public"
XDG_DOCUMENTS_DIR="$HOME/Documents"
XDG_MUSIC_DIR="$HOME/Music"
XDG_PICTURES_DIR="$HOME/Pictures"
XDG_VIDEOS_DIR="$HOME/Videos"

Also, as said i have configured other music folders and the ~/.cover-thumbnailer/cover-thumbnailer.conf is

#Configuration written by Cover Thumbnailer GUI
#Please edit with caution

[MUSIC]
	enabled = Yes
	keepdefaulticon = Yes
	usegnomefolder = Yes
	cropimg = Yes
	makemosaic = Yes
	path = "/mnt/backupdisk/music/hindi"
	path = "/mnt/backupdisk/music/english"

[PICTURES]
	enabled = Yes
	keepdefaulticon = No
	usegnomefolder = No
	maxthumbs = 3

[OTHER]
	enabled = No

[IGNORED]
	dotted = No

[NEVERIGNORED]

**Comment by flozz** [comment]
Everything seems ok with your configs... 

There is maybe a bug in Cover Thumbnailer, I will take a look later :)

**Comment by vishytk** [comment]
ok

**Comment by iborg10103** [comment]
Same problem here, everything runs ok in Ubuntu 18.04 (gnome 3.28) but fails in Ubuntu 18.10 (gnome 3.30). 
user-dirs.dirs file exists and looks valid but I have a lot of folders in /tmp dir with names like 
```
/tmp/gnome-desktop-thumbnailer-0NZ4SZ/gnome-desktop-file-to-thumbnail.(null)
/tmp/gnome-desktop-thumbnailer-76F44/gnome-desktop-file-to-thumbnail.(null)
```

Running nautilus from command line shows:
```
(nautilus:17998): GnomeDesktop-WARNING **: 19:26:00.721: Could not remove /tmp/gnome-desktop-thumbnailer-2JO6SZ, thumbnailer \xa0\xf8	\u0004\xeaU left files in directory
(nautilus:17998): GnomeDesktop-WARNING **: 19:26:00.810: Could not remove /tmp/gnome-desktop-thumbnailer-GD07SZ, thumbnailer  left files in directory
(nautilus:17998): GnomeDesktop-WARNING **: 19:26:01.914: Could not remove /tmp/gnome-desktop-thumbnailer-L1A0SZ, thumbnailer @\xaa left files in directory
```
```

**Comment by dmzoneill** [comment]
same

**Comment by flozz** [comment]
This is probably caused by the recent sandboxing of thumbnailers by Nautilus. I updated it to fix things. It should work if you generate thumbnails manually (see the README of this repo for more info)
