### ISSUE TITLE
Preview for folder not showing in nautilus

### ISSUE THREAD

**Issue by josvanr** [flozz/cover-thumbnailer#3]
Hi, I just downloaded cover-thumbnailer because I wanted folder previews for images inside the folder. Unfortunately its only showing the default icon also if there are jpegs inside. Nautilus version is 3.26.4.

**Comment by josvanr** [comment]
I did some more digging. If I start nautilus from the command line, I can see some output from the script that says someting like 'cant find user-dirs.dirs file'. I went into the script and let it print to console the actual path it is using, it was something like /home/jos/.config/user-dirs.dirs . The file exists, I could edit the path with vim. But having the script print to console print os.path.isfile('/home/jos/.config/user-dirs.dirs') returns 'False'... I tried do chmod ugoa+rwx the file, but same result. Also tried to 'isfile' a diferent file that acutally exists, but also returns false. In a script that I run myself from the command line, the same 'isfile' retuns True. So apparently, when the script is called by  nautilus, it can't acces the file for some reason. Giving up for now...............

**Comment by josvanr** [comment]
never mind. I found the 'scripts' menu item in nautilus. Now it does make thumbnails. (for some folders, not for all, but why?)

**Comment by flozz** [comment]
Hello,

Cover Thumbnailer generates specific thumbnails for some directories only (Music, Image, and other folders that contains images with specific names). This can be configured through a GUI. Type `cover-thumbnailer-gui` in a terminal to configure it :)

**Comment by Drakon74** [comment]
Hello,

i have the same problem, though i also don't have a "scripts" menu item in the context menu in Nautilus. Using Ubuntu 18.04.4 and Nautilus 3.26.4. 

I can see that Nautilus wants to generate thumbnails now for folders (as there is a short loading icon before the standard folder icon gets displayed) but nothing more.

**Comment by flozz** [comment]
Since some GNOME version, Nautilus sandbox the Thumbnailers, causing various issues. I just released a new Cover Thumbnailer version that is able to work on Ubuntu 20.04, and that adds a button to manually generate thumbnails of a folder. It is the best I can do for Nautilus.

Also note that it works normally with Thunar and Caja.
