### ISSUE TITLE
Thumbnails are not generated on Ubuntu 20.04

### ISSUE THREAD

**Issue by alexislefebvre** [flozz/cover-thumbnailer#6]
I used `cover-thumbnailer` on Ubuntu 19.10 and it worked perfectly.

I upgraded to Ubuntu 20.04 and the package was removed. So I installed it through source, I was able to install but it doesn't work.

I think I found why by adding some debug code:

```diff
diff --git a/cover-thumbnailer.py b/cover-thumbnailer.py
index 5078307..8508d9d 100755
--- a/cover-thumbnailer.py
+++ b/cover-thumbnailer.py
@@ -693,8 +693,9 @@ if __name__ == "__main__":
             thumbnail.save_thumb(OUTPUT_FILE, "PNG")
 
     #Picture folders
-    elif CONF['pictures_enabled'] and match_path(INPUT_FOLDER, CONF['pictures_paths']):
+    elif CONF['pictures_enabled']:
         picture_list = search_cover(INPUT_FOLDER)
+        print(INPUT_FOLDER)
         if len(picture_list) == 0:
             picture_list = search_pictures(INPUT_FOLDER)
             if len(picture_list) == 0:
```

And when I clear thumbnails then launch `nautilus` from command line, it prints this:

```
/tmp/gnome-desktop-file-to-thumbnail
```

So it looks like `INPUT_FOLDER` doesn't contain the real input folder but `/tmp/gnome-desktop-file-to-thumbnail` instead, and this break folders detection.

**Comment by flozz** [comment]
Hum, it will be annoying if we can't have the real path of the input.... maybe it is a symbolic link and we can dereference it to have the real path?

**Comment by alexislefebvre** [comment]
I checked, thumbnails are generated for directories in `/home` and in `/mnt` that use a `cifs` mount. So it's not due to the way filesystem is mounted.

The file `/tmp/gnome-desktop-file-to-thumbnail` may be created since bubblewrap has been used:
- https://bugs.launchpad.net/ubuntu/+source/gnome-desktop3/+bug/1808702
- https://askubuntu.com/questions/1088539/custom-thumbnailers-don-t-work-on-ubuntu-18-10-and-18-04

**Comment by flozz** [comment]
Fixed in **Cover-Thumbnailer v0.10.0** :)

**Comment by alexislefebvre** [comment]
The [README](https://github.com/flozz/cover-thumbnailer/tree/0d0307612774d06f2d8181e89717fe78f8d8dafd#generating-thumbnails) now says this:

> If you are using Nautilus, thumbnails cannot be generated automatically in most recent version of this file browser. You can generate thumbnails manually using the configuration tool: in the last tab, just click the "Select a folder and generate thumbnails" button.

I installed cover-thumbnailer from source before last week update and it works with Nautilus. What version of Nautilus do you use? Here's mine:

```shell
$ nautilus --version
GNOME nautilus 3.36.3
```

**Comment by flozz** [comment]
I use the same version... Maybe in some cases (migration? distribution?) the sandbox is not used. So at least it work manually, and if it work automatically for some people... it's better :)

**Comment by alexislefebvre** [comment]
:fr: 

Je viens de voir [ton billet sur linuxfr.org](https://linuxfr.org/news/sortie-de-cover-thumbnailer-v0-10-0). C'était très interessant, merci. :slightly_smiling_face: 

> Le premier problème est causé par Nautilus : pour des raisons de sécurité, les développeurs ont décidé d’exécuter les thumbnailers (générateurs de miniatures) dans des sandbox (bacs à sable) pour les isoler du système. Cela pose divers problèmes dans le cas de Cover Thumbnailer :
>
> - il a besoin de connaître le chemin réel du dossier pour lequel on lui demande de générer une miniature (pour savoir s’il faut générer une miniature d’album de musique ou une prévisualisation d’un dossier d’images) ;
> - il doit pouvoir accéder à son fichier de configuration.

C'était aussi cassé chez moi en fait, j'avais enlevé ` and match_path(INPUT_FOLDER, CONF['pictures_paths'])` dans le code pour que ça fonctionne.

Est-ce qu'on peut imaginer un mode dégradé pour Nautilus ? Par exemple :
- s'il y a un fichier `folder.jpg`, ça affiche l'image en grand
- sinon, ça affiche 1 à 2 images (perso, je trouve que 4 images c'est peu lisible, limiter à 1 ou 2 ça permettrait de simplifier pas mal de code)

**Comment by flozz** [comment]
Ça me parait difficile à faire : déjà il faudrait être capable de détecter que le progamme a été appelé par Nautilus (pour éviter de perturber le fonctionnement avec les autres navigateurs de fichiers), et en suite, bah tout le monde ne veut pas des miniatures dans n'importe quel dossiers.

Pour régler le problème de Nautilus il faudrait contourner la sandbox... C'est faisable mais j'ai pas le temps de m'occuper de ça pour l'instant ^^'

**Comment by alexislefebvre** [comment]
Il y a une solution de bricolage pour monter un répertoire dans la sandbox : https://gitlab.gnome.org/GNOME/gnome-desktop/-/issues/90

Une PR en cours pourrait faciliter ce montage : https://gitlab.gnome.org/GNOME/gnome-desktop/-/merge_requests/80

**Comment by flozz** [comment]
Ça ne résoud malheureusement pas notre problème principal : 

Cover Thumbnailer à besoin de connaitre le véritable chemin du dossier pour déterminer comment l'afficher (pochette de CD, carton à dessin,...)

Et en entrée, Nautilus lui donne ceci en paramètre : 

![Capture d’écran de 2020-08-06 09-20-34](https://user-images.githubusercontent.com/971438/89502979-2ad01d80-d7c6-11ea-814f-b1b6f62b5789.png)

Soit un chemin dans /tmp, alors que le dossier pour lequel il essayait de faire une miniature se trouvait dans `~/Music`
